### ISSUE TITLE
Why is filter query param required?

### ISSUE THREAD

**Issue by quantumew** [imulab/go-scim#12]
Am I reading the spec wrong? This project requires a `filter` query param on the GET /Users endpoint but the spec says `A query against a server root indicates that all resources within the server SHALL be included, subject to filtering.`

**Comment by quantumew** [comment]
A bit more info, the IdP I am using is sending this test query GET `/v2/Users?startIndex=1&count=2` and it is resulting in a 400. According to the spec I believe this is a valid query.

**Comment by imulab** [comment]
Assigning it as a bug to test it out in v2.

**Comment by imulab** [comment]
Addressed in the v2 version to be release in a couple of days, closing this one.
