### ISSUE TITLE
ResourceTypes endpoint responds with incorrect body

### ISSUE THREAD

**Issue by quantumew** [imulab/go-scim#14]
I am using the built in ResourceTypes handler. [It is hardcoded to respond with a list of the resource types](https://github.com/imulab/go-scim/blob/master/handlers/resource_type.go#L18-L25). According to the spec this is wrong https://tools.ietf.org/html/rfc7644#section-4. Am I missing something?

It should be a list response:
```
  {
    "totalResults":2,
    "itemsPerPage":10,
    "startIndex":1,
    "schemas":["urn:ietf:params:scim:api:messages:2.0:ListResponse"],
    "Resources":[{
      "schemas": ["urn:ietf:params:scim:schemas:core:2.0:ResourceType"],
      "id":"User",
      "name":"User",
      "endpoint": "/Users",
      "description": "User Account",
      "schema": "urn:ietf:params:scim:schemas:core:2.0:User",
      "schemaExtensions": [{
        "schema":
          "urn:ietf:params:scim:schemas:extension:enterprise:2.0:User",
        "required": true
      }],
      "meta": {
        "location":"https://example.com/v2/ResourceTypes/User",
        "resourceType": "ResourceType"
      }
    },
   {
     "schemas": ["urn:ietf:params:scim:schemas:core:2.0:ResourceType"],
     "id":"Group",
     "name":"Group",
     "endpoint": "/Groups",
     "description": "Group",
     "schema": "urn:ietf:params:scim:schemas:core:2.0:Group",
     "meta": {
       "location":"https://example.com/v2/ResourceTypes/Group",
       "resourceType": "ResourceType"
     }
   }]
  }
```

**Comment by quantumew** [comment]
Seeing a similar theme on the `/Schemas` endpoint as well.

**Comment by q-uint** [comment]
You are correct.

Resource Type Representation [Section 8.6](https://tools.ietf.org/html/rfc7643#section-8.6)

> The following is a non-normative example of the SCIM resource types in JSON format.

The `/Schemas` and `/ResourceTypes` endpoints should return a ListResponse.

Service Provider Config Endpoints [Section 4](https://tools.ietf.org/html/rfc7644#section-4)

> When returning multiple ResourceTypes or Schemas, the message form described by the "urn:ietf:params:scim:api:messages:2.0:ListResponse" (ListResponse) form SHALL be used.

**Comment by imulab** [comment]
You are right, this is a bug. However, I am currently working on v2 of this project which will supersede this version. I will mark it as a bug and make sure there's a test case against this in v2. Thanks again!

**Comment by imulab** [comment]
Hi folks, I am closing this one in favour of #40
