### ISSUE TITLE
How can handle Bearer tokens in the repository layer?

### ISSUE THREAD

**Issue by matbhz** [imulab/go-scim#31]
I have many different teams/apps that are going to use our company's SCIM APIs.

We had great success so far leveraging go-scim's `handler`, so we just needed to implement custom logic inside our `Repository` structs in order to CRUD SCIM Resources into our Resources.

We need, however, to identify which team these resources are part of  so they can be manage accordingly.

How can I read the `Authorization` header from a request and use its value in the repository layer?

Thanks!

**Comment by imulab** [comment]
Hi @matbhz 

I am assuming you are working with the stable v1.

Under `v1`, there is no quick and easy way of achieving that use case, as the repository interface only accepts a `DataProvider` object, so passing on this kind of transient data is difficult.

That being said, it might be possible if you override some request parsing functions in the handlers to sneak in a transient piece of data on the resource. For example, in the create handler

```
resource, err := ParseBodyAsResource(r)
ErrorCheck(err)

teamId := ParseTeamIdFromAuthorizationHeader(r)
resource.GetData()["_teamId"] = teamId
```

Then in your custom repository implementation, read that team id from the resource and proceed to your logic. You may want to clear this transient data before you proceed.

I am currently working on v2 of this project and will include `context.Context` in db interfaces, check out [here](https://github.com/imulab/go-scim/blob/v2.0.0-m3/protocol/db/db.go). In the future, if you would like to upgrade to v2, you can simply write an HTTP middleware to parse your teamId from the authorization header and attach that to the context. Then, this information will be available in your DB implementation.

Hope that helps.

**Comment by imulab** [comment]
closing.. feel free to reopen
