### ISSUE TITLE
InvalidDBRef

### ISSUE THREAD

**Issue by requaos** [imulab/go-scim#35]
What did I do:
```
curl --location --request PATCH 'http://localhost:5000/Groups/f709a088-20ef-4f31-8986-a72c3e65a4c6' \
--header 'Content-Type: application/javascript' \
--data-raw '{
  "schemas":[
    "urn:ietf:params:scim:api:messages:2.0:PatchOp"
  ],
  "Operations":[
    {
    "op":"add",
    "path":"members",
    "value":[{"value":"d3f3bb44-4583-41ba-920f-3319266ed435"}]
    }
  ]
}'
```

What did you expect:
The groupsync worker to add the group to the user.

What did you get:
```
{"level":"error","error":"(InvalidDBRef) The DBRef $ref field must be followed by a $id field","resourceId":"d3f3bb44-4583-41ba-920f-3319266ed435","resourceVersion":"W/\"08f6f4be51ef1c744e1c809dc7ca8b8c4136fea2\"","time":"2020-01-14T15:16:35Z","message":"failed to replace resource in mongo"}
{"level":"error","error":"(InvalidDBRef) The DBRef $ref field must be followed by a $id field","message":"&{GroupID:f709a088-20ef-4f31-8986-a72c3e65a4c6 MemberID:d3f3bb44-4583-41ba-920f-3319266ed435 Trial:1}","time":"2020-01-14T15:16:35Z","message":"error encountered while syncing user group, will requeue"}
{"level":"error","limit":1,"message":"{\"group_id\":\"f709a088-20ef-4f31-8986-a72c3e65a4c6\",\"member_id\":\"d3f3bb44-4583-41ba-920f-3319266ed435\",\"trial\":2}","trial":2,"time":"2020-01-14T15:16:35Z","message":"message had exceeded trial limit, will drop message"}
```

**Comment by requaos** [comment]
With regards to the `$ref` reference field in the `groups` complex field on the user schema. Is it the intention for this to be a `DBRef` field, or is it just a coincidence that the SCIM specification includes a field of this name?

If it is a coincidence, then we may be able to have `$ref` mapped to `ref` in the mongo document, so that we don't trip on the mongo built-in feature.

**Comment by requaos** [comment]
I just found the `/mongo/metadata.go`... is there an example of the expected format for the files in `MONGO_METADATA_FOLDER` ?

**Comment by requaos** [comment]
Something like this, maybe?
```
{
  "metadata": [
    {
      "id": "urn:ietf:params:scim:schemas:core:2.0:User:groups.$ref",
      "mongoName": "ref",
      "mongoPath": "groups.ref"
    },
    {
      "id": "urn:ietf:params:scim:schemas:core:2.0:Group:members.$ref",
      "mongoName": "ref",
      "mongoPath": "members.ref"
    }
  ]
}
```

**Comment by requaos** [comment]
Yep, this solved my issue. Since mongo is the only persistence store aside from in-memory (which I gather is only for testing?), I will attempt to add this to the `README.md` via pull-request in an non-obtrusive way.

**Comment by imulab** [comment]
Yes, the metadata feature in the MongoDB module was added to overcome the reserved keywords in MongoDB. I actually think it is already documented [here](https://github.com/imulab/go-scim/blob/master/mongo/README.md)

I am still working toward the last few features, hence only milestone versions for now. Please consider this a work-in-progress.

Glad you were able to solve it though, closing this issue...

**Comment by imulab** [comment]
Also, take a look [here](https://github.com/imulab/go-scim/tree/master/mongo/public), might just be what you need.
