### ISSUE TITLE
Error locating old resource for replacement in DB interface

### ISSUE THREAD

**Issue by imulab** [imulab/go-scim#37]
# Description

`Replace` method of `DB` interface only allows a single `*prop.Resource` parameter which is supposed to be the updated resource. This does not allow implementation to locate/lock the old resource from the database which was retrieved at the start of the replacement API call for reference usage, because `meta.version` was changed prior to calling `Replace`.

# Proposal

Change `Replace` method signature to `Replace(ctx context.Context, ref *prop.Resource, replacement *prop.Resource)` to allow implementation see the reference resource retrieved earlier.

Thanks for @requaos for noticing this issue and provide initial solution

**Comment by requaos** [comment]
In this proposed change, both `ref` and `replacement` are whole objects. Is it premature optimization to think that copying the `Version()` output before modifying, or to add an attribute to `prop.Resource` for the "previous" version, is a lighter lift that to allocate an entire object clone before modification just for the version output?

**Comment by imulab** [comment]
Hi @requaos 

I received the PR and will work on it shortly. I am currently working on a big refactor which will include this issue, will probably finish some time next week. Appreciate for the waiting, promise will get to it.

**Comment by imulab** [comment]
Addressing this issue in #39, closing this now.
