### ISSUE TITLE
Redis support

### ISSUE THREAD

**Issue by requaos** [imulab/go-scim#44]
@imulab I would like to work on an alternative to mongo by implementing a redis module that satisfies the same interface.
This thread should serve the purpose of a discussing the advantages and/or disadvantages of doing this.
My motivation is based on past experience in maintaining and managing mongo clusters at production scale. I still have nightmares...

**Comment by imulab** [comment]
On first thought, I would say It is easy to perform CRUD operations with a Redis implementation, but Query functions would be difficult. I don't expect the Redis implementation to be used as the primary persistence source, but rather as a cache layer, or in use cases where filter is not supported.

To coordinate between the main persistence source and the cache source, we can also introduce a wrapper implementation in `pkg/db`, something like `CacheAware(main db.DB, cache db.DB) db.DB`

**Comment by requaos** [comment]
@imulab Hrmm, I was wondering about the lift effort the query/filter features that the bson interface gives us for nearly no cost. So it wouldn't be easy to avoid using mongo entirely. Thank you for your candor.
