### ISSUE TITLE
Content-type is not the same as SCIM RFC Protocol

### ISSUE THREAD

**Issue by alexvalenzuela** [imulab/go-scim#53]
The `Content-Type` header should be `application/scim+json` according to [RFC Protocol](https://tools.ietf.org/html/rfc7644#section-8.1)

https://github.com/imulab/go-scim/blob/0df035783a57c245ef3658c31e854a15f804dca9/pkg/v2/handlerutil/response.go#L25

**Comment by imulab** [comment]
Overlooked that! Thanks...

**Comment by imulab** [comment]
@alexvalenzuelac issue is fixed in `pkg/v2.1.1`, thanks!
