### ISSUE TITLE
Patch.Validate() does not support patch operation that is not lowercase

### ISSUE THREAD

**Issue by alexvalenzuela** [imulab/go-scim#54]
Hi, after checking the method and compare to the [following commit](https://github.com/imulab/go-scim/commit/25f409fa7f5e7576ade4ddfae39dcc2ad2e84ef5), it seems that we also need to add [this line](https://github.com/imulab/go-scim/blob/0df035783a57c245ef3658c31e854a15f804dca9/pkg/v2/service/patch.go#L110), so both [`for range`](https://github.com/imulab/go-scim/blob/0df035783a57c245ef3658c31e854a15f804dca9/pkg/v2/service/patch.go#L190) for PATCH operations be in compliance.

The reason is that Azure Active Directory PATCH `op` is capitalized. Why do they do this since this is not SCIM compliant? No one knows.

See [here](https://docs.microsoft.com/en-us/azure/active-directory/app-provisioning/use-scim-to-provision-users-and-groups#update-user-multi-valued-properties) for more details.

**Comment by imulab** [comment]
Got it, will fix it with the next release.

**Comment by imulab** [comment]
@alexvalenzuelac issue is fixed in `pkg/v2.1.1`, thanks!
