### ISSUE TITLE
Multiple Attributes Selection

### ISSUE THREAD

**Issue by plamenGo** [imulab/go-scim#62]
Go-Scim can't seem to handle multiple attributes selection. A request like:

GET http://{{Server}}{{Port}}/{{Api}}/Users?attributes=userName,emails

Returns:

{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "status": 400,
    "scimType": "invalidPath",
    "detail": "invalidPath: error compiling path"
}

It breaks on the comma ',' between userName and emails. 

This test is from the Microsoft SCIM Reference Code Postman test collection: https://github.com/AzureAD/SCIMReferenceCode/wiki/Test-Your-SCIM-Endpoint

**Comment by imulab** [comment]
Yup that seems like a bug. I mistakenly [interpreted the delimiter as space](https://github.com/imulab/go-scim/blob/ba8bacdf9e460f0bbe05a59cf4ff11f9a4b22c42/pkg/v2/handlerutil/request.go#L30) rather than a comma.

I am travelling now, will fix this on return.

Marking it as a bug.

**Comment by imulab** [comment]
fixed and closed.
