### ISSUE TITLE
Scim filter with complex attribute query

### ISSUE THREAD

**Issue by perljusback** [imulab/go-scim#68]
When trying to use a complex attribute query in a filter ex.

**/Users?filter= emails%5Btype+eq+%22work%22%5D**

The filter exits with: invalid character '[' around position 0 (hint:invalid character in path)

**Comment by imulab** [comment]
Please see [this comment](https://github.com/imulab/go-scim/issues/64#issuecomment-623888146).

Closing this one for now as I suspect it won't be relevant.
