### ISSUE TITLE
Update and search operations fail when attributes contain dot

### ISSUE THREAD

**Issue by alelb** [imulab/go-scim#7]
Hi @davidiamyou,

I noticed some issues using attributes that contain a dot in its own name (ie when I use the urn for extension attributes, using `urn:ietf:params:scim:schemas:extension:enterprise:2.0:User` like a complex attribute).

**Mongodb** does not allow the `.` within the attribute name, so: 
* Update fails if one of  the attribute of your resource contains a `.`
* Search fails if you are searching for an attribute contains a `.`

I think a solution would be to set up a mapping between the attribute actual name and the key used within db (avoiding the usage of `.` in the db key string for mongodb, may be another db could have issue with other chars).

Could "assist" custom property suitable to support this mapping?

Have you some tips?

**Comment by imulab** [comment]
You are right, I haven't thought about that. And if mongo rejects dot within field names, it is certainly going to be a design flaw.

One way I can think of is to use a "dbName" assist field on the container of schema extension attributes. The implementation will be a bit different for v2, as I am separating out the definition of schema/schema extensions, resource type, and assist metadata into separate structures to allow cleaner definitions.

But thanks for bringing this up. I will make sure there's a test case for it in v2.

**Comment by imulab** [comment]
MongoDB metadata feature is included in v2, to be release in a few days, closing this one.
