### ISSUE TITLE
Azure AD Patch request issues

### ISSUE THREAD

**Issue by plamenGo** [imulab/go-scim#75]
Hey, Azure posts the following when trying to PATCH a user:

```
{
"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
"Operations":[{
        "op":"Add","path":"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:manager",
        "value":"45619541-95de-4d5e-9872-571b5d2c5577"}]
}

```

We are unable to parse and the get following error from go-scim:

```
{
    "schemas": [
        "urn:ietf:params:scim:api:messages:2.0:Error"
    ],
    "status": 400,
    "scimType": "invalidPath",
    "detail": "invalidPath: error compiling path"
}
```

I think the issue might be that manager is a complex attribute under the enterprise schema, but is sent over with a simple ID.

Do you know if this is a bug in go-scim of if we should format the PATCH request differently? Can you provide an example of what this request should look like so it works in go-scim. 

Best Regards!
Plamen

**Comment by plamenGo** [comment]
Same thing happens with the employee number field.

`{"schemas":["urn:ietf:params:scim:api:messages:2.0:PatchOp"],"Operations":[{"op":"Add","path":"urn:ietf:params:scim:schemas:extension:enterprise:2.0:User:employeeNumber","value":"6546579"}]}`

This is not a complex field, so this leads me to believe that we're just not processing the path correctly

**Comment by plamenGo** [comment]
After digging some more it seems that the path compiler does not like the colons (:) in the path name -- it's not clear to me what I should do about it though. I suspect the (.) may trip it up as well. Any advice would be welcome!

**Comment by imulab** [comment]
@plamenGo looks like a very legit request, will take a look at this the day after.

**Comment by ricardoamador** [comment]
Why is this closed. This is still an issue. I assume that this repo is defunct?
```
"FunctionName":"github.com/haystackteam/haystack/backend/server/scimlegacy.PatchUser", 
"HttpMethod":"PATCH", 
"LineNumber":260, 
"LogId":"b61b87e1-b0fb-44a0-a77d-3467d8b678bf", 
"Message":"patch resource error. resource type = User, error = invalidSyntax: expects null (pos:39)"
```
