### ISSUE TITLE
Error on startup 

### ISSUE THREAD

**Issue by thawkins** [imulab/go-scim#8]
Im trying to get this running, but i cant seem to get it to startup. 

i have a mongodb 4.0.8 server running locally on localhost:27017 

but when i run the scim server i get 

[thawkins@localhost example]$ go run server.go
panic: no reachable servers

goroutine 1 [running]:
github.com/davidiamyou/go-scim/handlers.ErrorCheck(...)
	/home/thawkins/go/src/github.com/davidiamyou/go-scim/handlers/shared.go:55
main.initConfiguration()
	/home/thawkins/go/src/github.com/davidiamyou/go-scim/example/server.go:69 +0x19ce
main.main()
	/home/thawkins/go/src/github.com/davidiamyou/go-scim/example/server.go:102 +0x26
exit status 2

Any Ideas 

Fedora 29, using latest go

**Comment by imulab** [comment]
Totally missed this ticket. Did you get it to work? It sounds like the driver wasn't able to reach your server. Could you verify that `localhost:2017` is reachable by using a native Mongo client to connect to it?

**Comment by imulab** [comment]
Closing the issue now. Feel free to reopen if there's more activity.
