### ISSUE TITLE
MongoDB operator constant is wrong, and fixing it breaks tests

### ISSUE THREAD

**Issue by dcormier** [imulab/go-scim#81]
![image](https://user-images.githubusercontent.com/216265/102546265-6092e600-4085-11eb-8ae7-af4ff870f228.png)

[This](https://github.com/imulab/go-scim/blob/master/mongo/v2/filter.go#L403) should be `mongoNot = "$not"`, rather than `mongoNot = "$nor"`.

I'm working with a fork of this and changing it caused some tests to fail. it makes me concerned that the tests are wrong, since all the functions involved say `not`, rather than `nor`. I don't have time fix it and submit a PR here, unfortunately.

**Comment by imulab** [comment]
You are probably right. I haven't been working on this project for a while, so my memory could have fade a bit.

The original intention is that the `$nor` operator could use multiple sub-expressions while `$not` could only use one. But it seems the SCIM `not` only uses one anyways, so I suppose I could just use `$not`.

Bug reports with failing tests are always welcomed, although it may be some time before I can turn around to this project.
